from netkatana.types import DnsRule, HttpRule, Severity, TlsRule
from netkatana.validators.dns import dmarc_missing, dmarc_multiple, spf_missing, spf_multiple, spf_permissive
from netkatana.validators.http.headers.csp import (
    csp_base_uri_missing,
    csp_block_all_mixed_content_deprecated,
    csp_child_src_hash_invalid,
    csp_child_src_missing,
    csp_child_src_nonce_invalid,
    csp_child_src_source_insecure_scheme,
    csp_child_src_source_ip,
    csp_child_src_unrestricted,
    csp_connect_src_missing,
    csp_connect_src_unrestricted,
    csp_duplicated,
    csp_font_src_hash_invalid,
    csp_font_src_missing,
    csp_font_src_nonce_invalid,
    csp_font_src_source_insecure_scheme,
    csp_font_src_source_ip,
    csp_font_src_unrestricted,
    csp_form_action_hash_invalid,
    csp_form_action_missing,
    csp_form_action_nonce_invalid,
    csp_form_action_source_insecure_scheme,
    csp_form_action_source_ip,
    csp_form_action_unrestricted,
    csp_frame_ancestors_missing,
    csp_img_src_missing,
    csp_img_src_unrestricted,
    csp_missing,
    csp_object_src_unsafe,
    csp_report_only_base_uri_missing,
    csp_report_only_block_all_mixed_content_deprecated,
    csp_report_only_child_src_hash_invalid,
    csp_report_only_child_src_missing,
    csp_report_only_child_src_nonce_invalid,
    csp_report_only_child_src_source_insecure_scheme,
    csp_report_only_child_src_source_ip,
    csp_report_only_child_src_unrestricted,
    csp_report_only_connect_src_missing,
    csp_report_only_connect_src_unrestricted,
    csp_report_only_duplicated,
    csp_report_only_font_src_hash_invalid,
    csp_report_only_font_src_missing,
    csp_report_only_font_src_nonce_invalid,
    csp_report_only_font_src_source_insecure_scheme,
    csp_report_only_font_src_source_ip,
    csp_report_only_font_src_unrestricted,
    csp_report_only_form_action_hash_invalid,
    csp_report_only_form_action_missing,
    csp_report_only_form_action_nonce_invalid,
    csp_report_only_form_action_source_insecure_scheme,
    csp_report_only_form_action_source_ip,
    csp_report_only_form_action_unrestricted,
    csp_report_only_frame_ancestors_missing,
    csp_report_only_img_src_missing,
    csp_report_only_img_src_unrestricted,
    csp_report_only_object_src_unsafe,
    csp_report_only_script_src_missing,
    csp_report_only_script_src_unrestricted,
    csp_report_only_style_src_missing,
    csp_report_only_style_src_unrestricted,
    csp_report_only_unsafe_eval,
    csp_report_only_unsafe_inline,
    csp_report_only_worker_src_missing,
    csp_report_only_worker_src_unrestricted,
    csp_script_src_missing,
    csp_script_src_unrestricted,
    csp_style_src_missing,
    csp_style_src_unrestricted,
    csp_unsafe_eval,
    csp_unsafe_inline,
    csp_worker_src_missing,
    csp_worker_src_unrestricted,
)
from netkatana.validators.http.headers.general import (
    access_control_allow_credentials_invalid,
    access_control_allow_credentials_wildcard,
    access_control_allow_methods_unsafe,
    access_control_allow_origin_null,
    access_control_allow_origin_wildcard,
    access_control_max_age_excessive,
    coep_credentialless,
    coep_invalid,
    coep_missing,
    coep_ro_credentialless,
    coep_ro_invalid,
    coep_ro_unsafe_none,
    coep_unsafe_none,
    cookie_httponly_missing,
    cookie_invalid,
    cookie_prefix_host_misconfigured,
    cookie_prefix_secure_misconfigured,
    cookie_samesite_missing,
    cookie_secure_missing,
    coop_invalid,
    coop_missing,
    coop_noopener_allow_popups,
    coop_ro_invalid,
    coop_ro_noopener_allow_popups,
    coop_ro_same_origin_allow_popups,
    coop_ro_unsafe_none,
    coop_same_origin_allow_popups,
    coop_unsafe_none,
    corp_cross_origin,
    corp_invalid,
    corp_missing,
    corp_same_site,
    hsts_duplicated,
    hsts_include_subdomains_missing,
    hsts_invalid,
    hsts_max_age_low,
    hsts_max_age_zero,
    hsts_missing,
    hsts_preload_not_eligible,
    referrer_policy_invalid,
    referrer_policy_missing,
    referrer_policy_unsafe,
    server_disclosure,
    x_content_type_options_duplicated,
    x_content_type_options_invalid,
    x_content_type_options_missing,
    x_frame_options_duplicated,
    x_frame_options_invalid,
    x_frame_options_missing,
    x_powered_by_disclosure,
)
from netkatana.validators.http.response import (
    redirect_chain_long,
    redirect_chain_mixed_schemes,
    redirect_https_downgrade,
    status_server_error,
)
from netkatana.validators.tls import (
    tls_cert_expired,
    tls_cert_mismatched,
    tls_cert_revoked,
    tls_cert_self_signed,
    tls_cert_untrusted,
    tls_cipher_weak,
    tls_version_deprecated,
    tls_version_outdated,
)

http_rules = [
    HttpRule(
        code="headers_hsts_missing",
        severity=Severity.CRITICAL,
        detail="The 'Strict-Transport-Security' header instructs browsers to always use HTTPS for this domain, preventing protocol downgrade and SSL stripping attacks.",
        validator=hsts_missing,
    ),
    HttpRule(
        code="headers_hsts_invalid",
        severity=Severity.CRITICAL,
        detail="The 'Strict-Transport-Security' header requires a valid 'max-age' directive; a malformed header is silently ignored by browsers.",
        validator=hsts_invalid,
    ),
    HttpRule(
        code="headers_hsts_duplicated",
        severity=Severity.WARNING,
        detail="The 'Strict-Transport-Security' header should appear only once; duplicate instances create ambiguity and are handled inconsistently across intermediaries and clients.",
        validator=hsts_duplicated,
    ),
    HttpRule(
        code="headers_hsts_max_age_zero",
        severity=Severity.CRITICAL,
        detail="'max-age=0' instructs browsers to delete the cached HSTS policy, removing HTTPS enforcement for returning users.",
        validator=hsts_max_age_zero,
    ),
    HttpRule(
        code="headers_hsts_max_age_low",
        severity=Severity.WARNING,
        detail="The 'max-age' directive controls how long browsers enforce HTTPS for this domain; values below one year (31,536,000 s) leave a wider window for downgrade attacks between visits.",
        validator=hsts_max_age_low,
    ),
    HttpRule(
        code="headers_hsts_include_subdomains_missing",
        severity=Severity.NOTICE,
        detail="The 'includeSubDomains' directive extends HSTS to all subdomains; without it, subdomains are reachable over plain HTTP and parent-domain cookies may be intercepted.",
        validator=hsts_include_subdomains_missing,
    ),
    HttpRule(
        code="headers_hsts_preload_not_eligible",
        severity=Severity.WARNING,
        detail="The 'preload' directive signals intent to join browser preload lists, which hardcode the HSTS policy before a user's first visit; qualifying requires 'max-age' ≥ 31,536,000 s and 'includeSubDomains'.",
        validator=hsts_preload_not_eligible,
    ),
    HttpRule(
        code="headers_csp_missing",
        severity=Severity.WARNING,
        detail="The 'Content-Security-Policy' header restricts which resources browsers can load, reducing the risk of XSS and data injection attacks.",
        validator=csp_missing,
    ),
    HttpRule(
        code="headers_csp_duplicated",
        severity=Severity.CRITICAL,
        detail="The 'Content-Security-Policy' header should appear only once; duplicate instances create ambiguity and are handled inconsistently across browsers and intermediaries.",
        validator=csp_duplicated,
    ),
    HttpRule(
        code="headers_csp_report_only_duplicated",
        severity=Severity.CRITICAL,
        detail="The 'Content-Security-Policy-Report-Only' header should appear only once; duplicate instances create ambiguity and can distort rollout signals.",
        validator=csp_report_only_duplicated,
    ),
    HttpRule(
        code="headers_csp_base_uri_missing",
        severity=Severity.WARNING,
        detail="'base-uri' restricts the <base> element's 'href', preventing attackers from redirecting relative resource loads and bypassing 'script-src'; it does not fall back to 'default-src'.",
        validator=csp_base_uri_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_base_uri_missing",
        severity=Severity.WARNING,
        detail="'base-uri' restricts the <base> element's 'href', preventing attackers from redirecting relative resource loads and bypassing 'script-src'; it does not fall back to 'default-src'.",
        validator=csp_report_only_base_uri_missing,
    ),
    HttpRule(
        code="headers_csp_block_all_mixed_content_deprecated",
        severity=Severity.WARNING,
        detail="'block-all-mixed-content' is deprecated in favor of 'upgrade-insecure-requests'; relying on it preserves older mixed-content behavior and complicates CSP maintenance.",
        validator=csp_block_all_mixed_content_deprecated,
    ),
    HttpRule(
        code="headers_csp_report_only_block_all_mixed_content_deprecated",
        severity=Severity.WARNING,
        detail="'block-all-mixed-content' is deprecated in favor of 'upgrade-insecure-requests'; keeping it in report-only policies adds legacy noise without reflecting the modern upgrade path.",
        validator=csp_report_only_block_all_mixed_content_deprecated,
    ),
    HttpRule(
        code="headers_csp_child_src_missing",
        severity=Severity.WARNING,
        detail="'child-src' (falling back to 'default-src') restricts nested browsing contexts and workers in older CSP processing models; without either directive, those loads are not explicitly constrained.",
        validator=csp_child_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_child_src_missing",
        severity=Severity.WARNING,
        detail="'child-src' (falling back to 'default-src') restricts nested browsing contexts and workers in older CSP processing models; without either directive, report-only telemetry does not model those restrictions.",
        validator=csp_report_only_child_src_missing,
    ),
    HttpRule(
        code="headers_csp_unsafe_inline",
        severity=Severity.CRITICAL,
        detail="'unsafe-inline' in 'script-src' (or 'default-src') permits all inline scripts; a nonce or hash neutralizes it and restores XSS protection in CSP Level 2+ browsers.",
        validator=csp_unsafe_inline,
    ),
    HttpRule(
        code="headers_csp_report_only_unsafe_inline",
        severity=Severity.CRITICAL,
        detail="'unsafe-inline' in 'script-src' (or 'default-src') permits all inline scripts; a nonce or hash neutralizes it and restores XSS protection in CSP Level 2+ browsers.",
        validator=csp_report_only_unsafe_inline,
    ),
    HttpRule(
        code="headers_csp_child_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', 'http:', 'wss:', or 'ws:') in 'child-src' (or 'default-src') allows nested browsing contexts and workers from broad origins, weakening CSP's containment of embedded content.",
        validator=csp_child_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_child_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', 'http:', 'wss:', or 'ws:') in 'child-src' (or 'default-src') allows nested browsing contexts and workers from broad origins, so report-only telemetry models a weak child policy.",
        validator=csp_report_only_child_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_child_src_source_nonce_invalid",
        severity=Severity.WARNING,
        detail="Nonce sources in 'child-src' (or 'default-src') must use valid CSP nonce syntax; malformed nonces signal an invalid allowlist entry that browsers will not interpret as intended.",
        validator=csp_child_src_nonce_invalid,
    ),
    HttpRule(
        code="headers_csp_report_only_child_src_source_nonce_invalid",
        severity=Severity.WARNING,
        detail="Nonce sources in 'child-src' (or 'default-src') must use valid CSP nonce syntax; malformed nonces mean report-only telemetry is modeling an invalid allowlist entry.",
        validator=csp_report_only_child_src_nonce_invalid,
    ),
    HttpRule(
        code="headers_csp_child_src_source_hash_invalid",
        severity=Severity.CRITICAL,
        detail="Hash sources in 'child-src' (or 'default-src') must use a supported algorithm and valid CSP hash syntax; malformed hashes create allowlist entries that browsers will not interpret as intended.",
        validator=csp_child_src_hash_invalid,
    ),
    HttpRule(
        code="headers_csp_report_only_child_src_source_hash_invalid",
        severity=Severity.CRITICAL,
        detail="Hash sources in 'child-src' (or 'default-src') must use a supported algorithm and valid CSP hash syntax; malformed hashes mean report-only telemetry is modeling an invalid allowlist entry.",
        validator=csp_report_only_child_src_hash_invalid,
    ),
    HttpRule(
        code="headers_csp_child_src_source_insecure_scheme",
        severity=Severity.CRITICAL,
        detail="Sources in 'child-src' (or 'default-src') should not use insecure schemes such as 'http:' or 'ws:'; allowing nested content over plaintext weakens CSP's protection against interception and content injection.",
        validator=csp_child_src_source_insecure_scheme,
    ),
    HttpRule(
        code="headers_csp_report_only_child_src_source_insecure_scheme",
        severity=Severity.CRITICAL,
        detail="Sources in 'child-src' (or 'default-src') should not use insecure schemes such as 'http:' or 'ws:'; allowing them in report-only policies models a weak child loading policy.",
        validator=csp_report_only_child_src_source_insecure_scheme,
    ),
    HttpRule(
        code="headers_csp_child_src_source_ip",
        severity=Severity.WARNING,
        detail="IP address sources in 'child-src' (or 'default-src') are brittle and bypass hostname-based policy boundaries, making embedded child resource controls harder to audit and maintain.",
        validator=csp_child_src_source_ip,
    ),
    HttpRule(
        code="headers_csp_report_only_child_src_source_ip",
        severity=Severity.WARNING,
        detail="IP address sources in 'child-src' (or 'default-src') are brittle and bypass hostname-based policy boundaries, so report-only telemetry models a harder-to-audit child loading policy.",
        validator=csp_report_only_child_src_source_ip,
    ),
    HttpRule(
        code="headers_csp_font_src_missing",
        severity=Severity.NOTICE,
        detail="'font-src' (falling back to 'default-src') restricts which origins may provide web fonts; without either directive, injected font loads can reach arbitrary hosts.",
        validator=csp_font_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_font_src_missing",
        severity=Severity.NOTICE,
        detail="'font-src' (falling back to 'default-src') restricts which origins may provide web fonts; without either directive, report-only telemetry does not model font-load restrictions.",
        validator=csp_report_only_font_src_missing,
    ),
    HttpRule(
        code="headers_csp_font_src_unrestricted",
        severity=Severity.WARNING,
        detail="A wildcard source (*, 'https:', 'http:', 'wss:', or 'ws:') in 'font-src' (or 'default-src') allows fonts from broad origins, weakening a directive that is normally expected to be narrowly scoped.",
        validator=csp_font_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_font_src_unrestricted",
        severity=Severity.WARNING,
        detail="A wildcard source (*, 'https:', 'http:', 'wss:', or 'ws:') in 'font-src' (or 'default-src') allows fonts from broad origins, so report-only telemetry models a weak font policy.",
        validator=csp_report_only_font_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_font_src_source_nonce_invalid",
        severity=Severity.WARNING,
        detail="Nonce sources in 'font-src' (or 'default-src') must use valid CSP nonce syntax; malformed nonces signal an invalid allowlist entry that browsers will not interpret as intended.",
        validator=csp_font_src_nonce_invalid,
    ),
    HttpRule(
        code="headers_csp_report_only_font_src_source_nonce_invalid",
        severity=Severity.WARNING,
        detail="Nonce sources in 'font-src' (or 'default-src') must use valid CSP nonce syntax; malformed nonces mean report-only telemetry is modeling an invalid allowlist entry.",
        validator=csp_report_only_font_src_nonce_invalid,
    ),
    HttpRule(
        code="headers_csp_font_src_source_hash_invalid",
        severity=Severity.CRITICAL,
        detail="Hash sources in 'font-src' (or 'default-src') must use a supported algorithm and valid CSP hash syntax; malformed hashes create allowlist entries that browsers will not interpret as intended.",
        validator=csp_font_src_hash_invalid,
    ),
    HttpRule(
        code="headers_csp_report_only_font_src_source_hash_invalid",
        severity=Severity.CRITICAL,
        detail="Hash sources in 'font-src' (or 'default-src') must use a supported algorithm and valid CSP hash syntax; malformed hashes mean report-only telemetry is modeling an invalid allowlist entry.",
        validator=csp_report_only_font_src_hash_invalid,
    ),
    HttpRule(
        code="headers_csp_font_src_source_insecure_scheme",
        severity=Severity.CRITICAL,
        detail="Sources in 'font-src' (or 'default-src') should not use insecure schemes such as 'http:' or 'ws:'; allowing font loads over plaintext weakens policy integrity and content transport guarantees.",
        validator=csp_font_src_source_insecure_scheme,
    ),
    HttpRule(
        code="headers_csp_report_only_font_src_source_insecure_scheme",
        severity=Severity.CRITICAL,
        detail="Sources in 'font-src' (or 'default-src') should not use insecure schemes such as 'http:' or 'ws:'; allowing them in report-only policies models a weak font loading policy.",
        validator=csp_report_only_font_src_source_insecure_scheme,
    ),
    HttpRule(
        code="headers_csp_font_src_source_ip",
        severity=Severity.WARNING,
        detail="IP address sources in 'font-src' (or 'default-src') are brittle and bypass hostname-based policy boundaries, making font loading controls harder to audit and maintain.",
        validator=csp_font_src_source_ip,
    ),
    HttpRule(
        code="headers_csp_report_only_font_src_source_ip",
        severity=Severity.WARNING,
        detail="IP address sources in 'font-src' (or 'default-src') are brittle and bypass hostname-based policy boundaries, so report-only telemetry models a harder-to-audit font loading policy.",
        validator=csp_report_only_font_src_source_ip,
    ),
    HttpRule(
        code="headers_csp_form_action_missing",
        severity=Severity.WARNING,
        detail="'form-action' restricts which URLs forms may submit to, preventing data exfiltration via injected forms; it does not fall back to 'default-src'.",
        validator=csp_form_action_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_form_action_missing",
        severity=Severity.WARNING,
        detail="'form-action' restricts which URLs forms may submit to, preventing data exfiltration via injected forms; it does not fall back to 'default-src'.",
        validator=csp_report_only_form_action_missing,
    ),
    HttpRule(
        code="headers_csp_form_action_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', 'http:', 'wss:', or 'ws:') in 'form-action' allows submissions to broad destinations, weakening a control intended to constrain form exfiltration paths.",
        validator=csp_form_action_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_form_action_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', 'http:', 'wss:', or 'ws:') in 'form-action' allows submissions to broad destinations, so report-only telemetry models a weak form submission policy.",
        validator=csp_report_only_form_action_unrestricted,
    ),
    HttpRule(
        code="headers_csp_form_action_source_nonce_invalid",
        severity=Severity.WARNING,
        detail="Nonce sources in 'form-action' must use valid CSP nonce syntax; malformed nonces signal an invalid allowlist entry that browsers will not interpret as intended.",
        validator=csp_form_action_nonce_invalid,
    ),
    HttpRule(
        code="headers_csp_report_only_form_action_source_nonce_invalid",
        severity=Severity.WARNING,
        detail="Nonce sources in 'form-action' must use valid CSP nonce syntax; malformed nonces mean report-only telemetry is modeling an invalid allowlist entry.",
        validator=csp_report_only_form_action_nonce_invalid,
    ),
    HttpRule(
        code="headers_csp_form_action_source_hash_invalid",
        severity=Severity.CRITICAL,
        detail="Hash sources in 'form-action' must use a supported algorithm and valid CSP hash syntax; malformed hashes create allowlist entries that browsers will not interpret as intended.",
        validator=csp_form_action_hash_invalid,
    ),
    HttpRule(
        code="headers_csp_report_only_form_action_source_hash_invalid",
        severity=Severity.CRITICAL,
        detail="Hash sources in 'form-action' must use a supported algorithm and valid CSP hash syntax; malformed hashes mean report-only telemetry is modeling an invalid allowlist entry.",
        validator=csp_report_only_form_action_hash_invalid,
    ),
    HttpRule(
        code="headers_csp_form_action_source_insecure_scheme",
        severity=Severity.CRITICAL,
        detail="Sources in 'form-action' should not use insecure schemes such as 'http:' or 'ws:'; allowing form submissions over plaintext weakens confidentiality and integrity of submitted data.",
        validator=csp_form_action_source_insecure_scheme,
    ),
    HttpRule(
        code="headers_csp_report_only_form_action_source_insecure_scheme",
        severity=Severity.CRITICAL,
        detail="Sources in 'form-action' should not use insecure schemes such as 'http:' or 'ws:'; allowing them in report-only policies models a weak form submission policy.",
        validator=csp_report_only_form_action_source_insecure_scheme,
    ),
    HttpRule(
        code="headers_csp_form_action_source_ip",
        severity=Severity.WARNING,
        detail="IP address sources in 'form-action' are brittle and bypass hostname-based policy boundaries, making allowed form submission destinations harder to audit and maintain.",
        validator=csp_form_action_source_ip,
    ),
    HttpRule(
        code="headers_csp_report_only_form_action_source_ip",
        severity=Severity.WARNING,
        detail="IP address sources in 'form-action' are brittle and bypass hostname-based policy boundaries, so report-only telemetry models a harder-to-audit form submission policy.",
        validator=csp_report_only_form_action_source_ip,
    ),
    # REFACTOR POINT ENDS HERE
    HttpRule(
        code="headers_csp_unsafe_eval",
        severity=Severity.CRITICAL,
        detail="'unsafe-eval' in 'script-src' (or 'default-src') permits eval(), new Function(string), and similar dynamic code execution from strings.",
        validator=csp_unsafe_eval,
    ),
    HttpRule(
        code="headers_csp_report_only_unsafe_eval",
        severity=Severity.CRITICAL,
        detail="'unsafe-eval' in 'script-src' (or 'default-src') permits eval(), new Function(string), and similar dynamic code execution from strings.",
        validator=csp_report_only_unsafe_eval,
    ),
    HttpRule(
        code="headers_csp_object_src_unsafe",
        severity=Severity.WARNING,
        detail="'object-src' (or 'default-src') controls <object> and <embed> elements; plugin content runs outside the browser's normal security model and has historically enabled code execution.",
        validator=csp_object_src_unsafe,
    ),
    HttpRule(
        code="headers_csp_report_only_object_src_unsafe",
        severity=Severity.WARNING,
        detail="'object-src' (or 'default-src') controls <object> and <embed> elements; plugin content runs outside the browser's normal security model and has historically enabled code execution.",
        validator=csp_report_only_object_src_unsafe,
    ),
    HttpRule(
        code="headers_csp_frame_ancestors_missing",
        severity=Severity.WARNING,
        detail="'frame-ancestors' controls which origins can embed this page in a frame or iframe, preventing clickjacking; it does not fall back to 'default-src'.",
        validator=csp_frame_ancestors_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_frame_ancestors_missing",
        severity=Severity.WARNING,
        detail="'frame-ancestors' controls which origins can embed this page in a frame or iframe, preventing clickjacking; it does not fall back to 'default-src'.",
        validator=csp_report_only_frame_ancestors_missing,
    ),
    HttpRule(
        code="headers_csp_script_src_missing",
        severity=Severity.CRITICAL,
        detail="'script-src' (falling back to 'default-src') restricts which scripts browsers execute; without either directive, scripts are completely unrestricted.",
        validator=csp_script_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_script_src_missing",
        severity=Severity.CRITICAL,
        detail="'script-src' (falling back to 'default-src') restricts which scripts browsers execute; without either directive, scripts are completely unrestricted.",
        validator=csp_report_only_script_src_missing,
    ),
    HttpRule(
        code="headers_csp_script_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', or 'http:') in 'script-src' (or 'default-src') allows scripts from any origin, making the allowlist pointless.",
        validator=csp_script_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_script_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', or 'http:') in 'script-src' (or 'default-src') allows scripts from any origin, making the allowlist pointless.",
        validator=csp_report_only_script_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_style_src_missing",
        severity=Severity.CRITICAL,
        detail="'style-src' (falling back to 'default-src') restricts which stylesheets browsers load; without either directive, CSS injection and data exfiltration via url() probes are possible.",
        validator=csp_style_src_missing,
    ),
    HttpRule(
        code="headers_csp_style_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', or 'http:') in 'style-src' (or 'default-src') allows stylesheets from any origin, making the allowlist pointless.",
        validator=csp_style_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_style_src_missing",
        severity=Severity.CRITICAL,
        detail="'style-src' (falling back to 'default-src') restricts which stylesheets browsers load; without either directive, CSS injection and data exfiltration via url() probes are possible.",
        validator=csp_report_only_style_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_style_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', or 'http:') in 'style-src' (or 'default-src') allows stylesheets from any origin, making the allowlist pointless.",
        validator=csp_report_only_style_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_connect_src_missing",
        severity=Severity.CRITICAL,
        detail="'connect-src' (falling back to 'default-src') restricts fetch(), XHR, WebSocket, EventSource, sendBeacon(), and <a ping>; without either directive, data can be exfiltrated to arbitrary origins.",
        validator=csp_connect_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_connect_src_missing",
        severity=Severity.CRITICAL,
        detail="'connect-src' (falling back to 'default-src') restricts fetch(), XHR, WebSocket, EventSource, sendBeacon(), and <a ping>; without either directive, data can be exfiltrated to arbitrary origins.",
        validator=csp_report_only_connect_src_missing,
    ),
    HttpRule(
        code="headers_csp_connect_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', or 'http:') in 'connect-src' (or 'default-src') allows scripts to send data to any origin via XHR, fetch(), WebSockets, EventSource, or sendBeacon().",
        validator=csp_connect_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_connect_src_unrestricted",
        severity=Severity.CRITICAL,
        detail="A wildcard source (*, 'https:', or 'http:') in 'connect-src' (or 'default-src') allows scripts to send data to any origin via XHR, fetch(), WebSockets, EventSource, or sendBeacon().",
        validator=csp_report_only_connect_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_img_src_missing",
        severity=Severity.WARNING,
        detail="'img-src' (falling back to 'default-src') restricts which origins may provide images; without either directive, injected image loads can beacon requests to arbitrary hosts.",
        validator=csp_img_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_img_src_missing",
        severity=Severity.WARNING,
        detail="'img-src' (falling back to 'default-src') restricts which origins may provide images; without either directive, report-only telemetry does not model image-load restrictions.",
        validator=csp_report_only_img_src_missing,
    ),
    HttpRule(
        code="headers_csp_img_src_unrestricted",
        severity=Severity.WARNING,
        detail="A wildcard source (*, 'https:', or 'http:') in 'img-src' (or 'default-src') allows images from any origin, weakening CSP's ability to constrain outbound image requests.",
        validator=csp_img_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_img_src_unrestricted",
        severity=Severity.WARNING,
        detail="A wildcard source (*, 'https:', or 'http:') in 'img-src' (or 'default-src') allows images from any origin, so report-only telemetry models a weak image policy.",
        validator=csp_report_only_img_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_worker_src_missing",
        severity=Severity.NOTICE,
        detail="'worker-src' (falling back to 'child-src', then 'script-src', then 'default-src') restricts which URLs may create workers; without any effective directive, worker creation is not explicitly constrained.",
        validator=csp_worker_src_missing,
    ),
    HttpRule(
        code="headers_csp_report_only_worker_src_missing",
        severity=Severity.NOTICE,
        detail="'worker-src' (falling back to 'child-src', then 'script-src', then 'default-src') restricts which URLs may create workers; without any effective directive, report-only telemetry does not model worker restrictions.",
        validator=csp_report_only_worker_src_missing,
    ),
    HttpRule(
        code="headers_csp_worker_src_unrestricted",
        severity=Severity.WARNING,
        detail="A wildcard source (*, 'https:', or 'http:') in 'worker-src' (or its fallback chain) allows workers from any origin, broadening the script execution surface.",
        validator=csp_worker_src_unrestricted,
    ),
    HttpRule(
        code="headers_csp_report_only_worker_src_unrestricted",
        severity=Severity.WARNING,
        detail="A wildcard source (*, 'https:', or 'http:') in 'worker-src' (or its fallback chain) allows workers from any origin, so report-only telemetry models a broad worker policy.",
        validator=csp_report_only_worker_src_unrestricted,
    ),
    HttpRule(
        code="headers_server_disclosure",
        severity=Severity.NOTICE,
        detail="The 'Server' header exposes web server or framework details that can help attackers tailor reconnaissance and exploit selection.",
        validator=server_disclosure,
    ),
    HttpRule(
        code="headers_x_powered_by_disclosure",
        severity=Severity.NOTICE,
        detail="The 'X-Powered-By' header exposes implementation details such as frameworks or runtimes, increasing reconnaissance signal for attackers.",
        validator=x_powered_by_disclosure,
    ),
    HttpRule(
        code="headers_cors_allow_origin_wildcard",
        severity=Severity.WARNING,
        detail="A wildcard Access-Control-Allow-Origin header permits any website to read responses unless credentials are blocked, exposing data intended only for trusted origins.",
        validator=access_control_allow_origin_wildcard,
    ),
    HttpRule(
        code="headers_cors_allow_origin_null",
        severity=Severity.CRITICAL,
        detail="Access-Control-Allow-Origin: null trusts sandboxed iframes, data: URLs, file://, and opaque-origin documents, which can let untrusted contexts read sensitive responses.",
        validator=access_control_allow_origin_null,
    ),
    HttpRule(
        code="headers_cors_allow_credentials_wildcard",
        severity=Severity.CRITICAL,
        detail="Using Access-Control-Allow-Origin: * together with Access-Control-Allow-Credentials: true attempts to expose credentialed responses to any origin and indicates a broken CORS policy.",
        validator=access_control_allow_credentials_wildcard,
    ),
    HttpRule(
        code="headers_cors_allow_credentials_invalid",
        severity=Severity.WARNING,
        detail="Access-Control-Allow-Credentials only accepts the case-insensitive token 'true'; any other value is invalid and ignored by browsers, often masking a misconfigured credentialed CORS policy.",
        validator=access_control_allow_credentials_invalid,
    ),
    HttpRule(
        code="headers_cors_allow_methods_unsafe",
        severity=Severity.NOTICE,
        detail="Allowing unsafe methods such as PUT, PATCH, or DELETE cross-origin increases the impact of a CORS mistake by enabling state-changing requests from trusted origins.",
        validator=access_control_allow_methods_unsafe,
    ),
    HttpRule(
        code="headers_cors_max_age_excessive",
        severity=Severity.NOTICE,
        detail="Browsers cap Access-Control-Max-Age, but excessively large values still indicate intent to cache permissive preflight results for too long, delaying policy corrections after a mistake.",
        validator=access_control_max_age_excessive,
    ),
    HttpRule(
        code="headers_corp_missing",
        severity=Severity.NOTICE,
        detail="The 'Cross-Origin-Resource-Policy' header lets a resource declare which origins or sites may load it in 'no-cors' mode, reducing unintended cross-site embedding and read side channels.",
        validator=corp_missing,
    ),
    HttpRule(
        code="headers_corp_invalid",
        severity=Severity.CRITICAL,
        detail="The 'Cross-Origin-Resource-Policy' header only accepts the case-sensitive values 'same-origin', 'same-site', or 'cross-origin'; invalid values are ignored by browsers.",
        validator=corp_invalid,
    ),
    HttpRule(
        code="headers_corp_same_site",
        severity=Severity.NOTICE,
        detail="'same-site' allows resources to be loaded across origins within the same site, which is broader than 'same-origin' and relies on site boundaries rather than exact origin matching.",
        validator=corp_same_site,
    ),
    HttpRule(
        code="headers_corp_cross_origin",
        severity=Severity.WARNING,
        detail="'cross-origin' allows any site to load the resource in 'no-cors' mode, making the resource broadly embeddable across origins.",
        validator=corp_cross_origin,
    ),
    HttpRule(
        code="headers_coep_missing",
        severity=Severity.NOTICE,
        detail="The 'Cross-Origin-Embedder-Policy' header controls whether a document may load cross-origin subresources that have not explicitly opted in via CORS or CORP, enabling cross-origin isolation.",
        validator=coep_missing,
    ),
    HttpRule(
        code="headers_coep_invalid",
        severity=Severity.CRITICAL,
        detail="The 'Cross-Origin-Embedder-Policy' header only accepts the structured-header tokens 'unsafe-none', 'require-corp', or 'credentialless'; invalid values are ignored and fall back to no embedder policy.",
        validator=coep_invalid,
    ),
    HttpRule(
        code="headers_coep_unsafe_none",
        severity=Severity.WARNING,
        detail="'unsafe-none' leaves the document without COEP protection, so cross-origin 'no-cors' subresources do not need to opt in with CORP or CORS.",
        validator=coep_unsafe_none,
    ),
    HttpRule(
        code="headers_coep_credentialless",
        severity=Severity.NOTICE,
        detail="'credentialless' allows cross-origin 'no-cors' subresources to load without CORP when fetched without credentials, which is broader than 'require-corp'.",
        validator=coep_credentialless,
    ),
    HttpRule(
        code="headers_coep_report_only_invalid",
        severity=Severity.CRITICAL,
        detail="The 'Cross-Origin-Embedder-Policy-Report-Only' header only accepts the structured-header tokens 'unsafe-none', 'require-corp', or 'credentialless'; invalid values are ignored and provide no rollout signal.",
        validator=coep_ro_invalid,
    ),
    HttpRule(
        code="headers_coep_report_only_unsafe_none",
        severity=Severity.WARNING,
        detail="'unsafe-none' in report-only mode observes a policy that leaves the document without COEP protection, so reported behavior does not model an isolated deployment.",
        validator=coep_ro_unsafe_none,
    ),
    HttpRule(
        code="headers_coep_report_only_credentialless",
        severity=Severity.NOTICE,
        detail="'credentialless' in report-only mode observes a broader policy than 'require-corp', allowing cross-origin 'no-cors' subresources without credentials.",
        validator=coep_ro_credentialless,
    ),
    HttpRule(
        code="headers_coop_missing",
        severity=Severity.NOTICE,
        detail="The 'Cross-Origin-Opener-Policy' header controls whether top-level documents share a browsing context group with their opener, reducing XS-Leaks and unwanted cross-origin window references.",
        validator=coop_missing,
    ),
    HttpRule(
        code="headers_coop_invalid",
        severity=Severity.CRITICAL,
        detail="The 'Cross-Origin-Opener-Policy' header only accepts the structured-header tokens 'unsafe-none', 'same-origin', 'same-origin-allow-popups', or 'noopener-allow-popups'; invalid values are ignored by browsers.",
        validator=coop_invalid,
    ),
    HttpRule(
        code="headers_coop_unsafe_none",
        severity=Severity.WARNING,
        detail="'unsafe-none' leaves the document with the default opener policy, allowing broader browsing-context-group sharing and opener relationships.",
        validator=coop_unsafe_none,
    ),
    HttpRule(
        code="headers_coop_same_origin_allow_popups",
        severity=Severity.NOTICE,
        detail="'same-origin-allow-popups' is broader than 'same-origin', allowing the document to retain opener relationships to 'unsafe-none' popups such as OAuth or payment flows.",
        validator=coop_same_origin_allow_popups,
    ),
    HttpRule(
        code="headers_coop_noopener_allow_popups",
        severity=Severity.NOTICE,
        detail="'noopener-allow-popups' severs opener relationships, but it does not provide the same same-origin isolation model as 'same-origin' and does not by itself create cross-origin isolation.",
        validator=coop_noopener_allow_popups,
    ),
    HttpRule(
        code="headers_coop_report_only_invalid",
        severity=Severity.CRITICAL,
        detail="The 'Cross-Origin-Opener-Policy-Report-Only' header only accepts the structured-header tokens 'unsafe-none', 'same-origin', 'same-origin-allow-popups', or 'noopener-allow-popups'; invalid values are ignored and provide no rollout signal.",
        validator=coop_ro_invalid,
    ),
    HttpRule(
        code="headers_coop_report_only_unsafe_none",
        severity=Severity.WARNING,
        detail="'unsafe-none' in report-only mode observes a policy that leaves the document with the default opener behavior, so reported behavior does not model an isolated deployment.",
        validator=coop_ro_unsafe_none,
    ),
    HttpRule(
        code="headers_coop_report_only_same_origin_allow_popups",
        severity=Severity.NOTICE,
        detail="'same-origin-allow-popups' in report-only mode observes a looser policy than 'same-origin', preserving opener relationships to 'unsafe-none' popups.",
        validator=coop_ro_same_origin_allow_popups,
    ),
    HttpRule(
        code="headers_coop_report_only_noopener_allow_popups",
        severity=Severity.NOTICE,
        detail="'noopener-allow-popups' in report-only mode is not applied by the current HTML processing model, so it provides little or no rollout signal.",
        validator=coop_ro_noopener_allow_popups,
    ),
    HttpRule(
        code="headers_x_content_type_options_missing",
        severity=Severity.WARNING,
        detail="The 'X-Content-Type-Options' header with value 'nosniff' disables MIME sniffing for scripts and styles, reducing exposure to content-type confusion attacks.",
        validator=x_content_type_options_missing,
    ),
    HttpRule(
        code="headers_x_content_type_options_invalid",
        severity=Severity.CRITICAL,
        detail="The 'X-Content-Type-Options' header only accepts the token 'nosniff'; invalid values are ignored by browsers and provide no MIME-sniffing protection.",
        validator=x_content_type_options_invalid,
    ),
    HttpRule(
        code="headers_x_content_type_options_duplicated",
        severity=Severity.CRITICAL,
        detail="The 'X-Content-Type-Options' header should appear only once; duplicate instances create ambiguity and are handled inconsistently across intermediaries and clients.",
        validator=x_content_type_options_duplicated,
    ),
    HttpRule(
        code="headers_referrer_policy_missing",
        severity=Severity.NOTICE,
        detail="The 'Referrer-Policy' header controls how much referrer information browsers send on navigations and subresource requests, reducing origin and path leakage to other sites.",
        validator=referrer_policy_missing,
    ),
    HttpRule(
        code="headers_referrer_policy_invalid",
        severity=Severity.WARNING,
        detail="The 'Referrer-Policy' header only accepts a defined policy token; invalid values are ignored and fall back to the user agent or document default policy.",
        validator=referrer_policy_invalid,
    ),
    HttpRule(
        code="headers_referrer_policy_unsafe",
        severity=Severity.WARNING,
        detail="Policies weaker than 'strict-origin-when-cross-origin' send more referrer information than the modern baseline, increasing cross-origin origin, path, or query leakage.",
        validator=referrer_policy_unsafe,
    ),
    HttpRule(
        code="headers_x_frame_options_missing",
        severity=Severity.WARNING,
        detail="The 'X-Frame-Options' header asks browsers to block framing or restrict it to the same origin, reducing clickjacking exposure in browsers that still enforce it.",
        validator=x_frame_options_missing,
    ),
    HttpRule(
        code="headers_x_frame_options_invalid",
        severity=Severity.WARNING,
        detail="The 'X-Frame-Options' header only accepts the tokens 'DENY' or 'SAMEORIGIN'; other values are ignored by modern browsers and provide no framing protection.",
        validator=x_frame_options_invalid,
    ),
    HttpRule(
        code="headers_x_frame_options_duplicated",
        severity=Severity.CRITICAL,
        detail="The 'X-Frame-Options' header should appear only once; duplicate instances create ambiguity and are handled inconsistently across browsers.",
        validator=x_frame_options_duplicated,
    ),
    HttpRule(
        code="headers_cookie_secure_missing",
        severity=Severity.CRITICAL,
        detail="The 'Secure' attribute ensures a cookie is sent only over HTTPS; without it, the cookie can be exposed on plain HTTP requests and intercepted by network attackers.",
        validator=cookie_secure_missing,
    ),
    HttpRule(
        code="headers_cookie_httponly_missing",
        severity=Severity.WARNING,
        detail="The 'HttpOnly' attribute prevents JavaScript from reading a cookie through the DOM, reducing session theft through XSS.",
        validator=cookie_httponly_missing,
    ),
    HttpRule(
        code="headers_cookie_samesite_missing",
        severity=Severity.WARNING,
        detail="The 'SameSite' attribute restricts when cookies are sent on cross-site requests, reducing CSRF and some cross-site navigation leaks.",
        validator=cookie_samesite_missing,
    ),
    HttpRule(
        code="headers_cookie_prefix_secure_misconfigured",
        severity=Severity.CRITICAL,
        detail="A cookie name starting with '__Secure-' must include the 'Secure' attribute; otherwise the prefix contract is broken and browsers may reject or ignore the intended hardening.",
        validator=cookie_prefix_secure_misconfigured,
    ),
    HttpRule(
        code="headers_cookie_prefix_host_misconfigured",
        severity=Severity.CRITICAL,
        detail="A cookie name starting with '__Host-' must include 'Secure', omit 'Domain', and set 'Path=/' so it remains host-only and cannot be widened to sibling subdomains or narrower paths.",
        validator=cookie_prefix_host_misconfigured,
    ),
    HttpRule(
        code="headers_cookie_invalid",
        severity=Severity.WARNING,
        detail="A malformed 'Set-Cookie' header can be ignored or interpreted inconsistently by clients, leaving the intended cookie policy partially or fully unapplied.",
        validator=cookie_invalid,
    ),
    HttpRule(
        code="response_status_server_error",
        severity=Severity.WARNING,
        detail="A 5xx response indicates a server-side failure; beyond availability impact, error paths often expose unstable behavior or operational problems worth investigating.",
        validator=status_server_error,
    ),
    HttpRule(
        code="response_redirect_https_downgrade",
        severity=Severity.CRITICAL,
        detail="A redirect from HTTPS to HTTP removes transport protection mid-navigation, exposing subsequent requests to interception and content tampering.",
        validator=redirect_https_downgrade,
    ),
    HttpRule(
        code="response_redirect_chain_long",
        severity=Severity.WARNING,
        detail="Long redirect chains add latency, create more failure points, and increase the chance that security headers or scheme expectations differ between hops.",
        validator=redirect_chain_long,
    ),
    HttpRule(
        code="response_redirect_chain_mixed_schemes",
        severity=Severity.WARNING,
        detail="Redirect chains that mix HTTP and HTTPS indicate inconsistent transport handling and can expose users to downgrade or cookie-scope surprises between hops.",
        validator=redirect_chain_mixed_schemes,
    ),
]

tls_rules = [
    TlsRule(
        code="tls_version_deprecated",
        severity=Severity.CRITICAL,
        detail="Versions SSL 3.0, TLS 1.0, and TLS 1.1 have known cryptographic weaknesses and are no longer accepted by modern security standards.",
        validator=tls_version_deprecated,
    ),
    TlsRule(
        code="tls_version_outdated",
        severity=Severity.WARNING,
        detail="TLS 1.2 remains widely supported, but TLS 1.3 removes legacy negotiation features, reduces handshake latency, and is the current recommended baseline.",
        validator=tls_version_outdated,
    ),
    TlsRule(
        code="tls_cert_expired",
        severity=Severity.CRITICAL,
        detail="An expired certificate can no longer prove the server's identity, so clients will reject the connection or warn the user.",
        validator=tls_cert_expired,
    ),
    TlsRule(
        code="tls_cert_self_signed",
        severity=Severity.WARNING,
        detail="A self-signed certificate is not anchored in a trusted CA hierarchy, so clients cannot verify the server's identity by default.",
        validator=tls_cert_self_signed,
    ),
    TlsRule(
        code="tls_cert_mismatched",
        severity=Severity.CRITICAL,
        detail="The certificate subject or SAN list must match the hostname being connected to; otherwise clients treat the connection as potentially intercepted.",
        validator=tls_cert_mismatched,
    ),
    TlsRule(
        code="tls_cert_revoked",
        severity=Severity.CRITICAL,
        detail="CAs can revoke certificates before they expire; clients that check revocation status will reject a revoked certificate.",
        validator=tls_cert_revoked,
    ),
    TlsRule(
        code="tls_cert_untrusted",
        severity=Severity.CRITICAL,
        detail="The TLS certificate chain must be traceable to a root CA trusted by the client; an unverifiable chain causes connection rejection.",
        validator=tls_cert_untrusted,
    ),
    TlsRule(
        code="tls_cipher_weak",
        severity=Severity.WARNING,
        detail="Cipher suites such as RC4, NULL, EXPORT, DES, 3DES, IDEA, and SEED have known weaknesses and should not be negotiated.",
        validator=tls_cipher_weak,
    ),
]

dns_rules = [
    DnsRule(
        code="dns_spf_missing",
        severity=Severity.NOTICE,
        detail="An SPF TXT record lists the servers authorized to send email for this domain; without it, mail servers cannot verify sender authenticity.",
        validator=spf_missing,
    ),
    DnsRule(
        code="dns_spf_multiple",
        severity=Severity.WARNING,
        detail="Publishing more than one SPF policy record is a misconfiguration; receivers treat SPF evaluation as invalid when multiple 'v=spf1' records are present.",
        validator=spf_multiple,
    ),
    DnsRule(
        code="dns_spf_permissive",
        severity=Severity.CRITICAL,
        detail="The '+all' mechanism in an SPF record authorizes any server on the internet to send email for this domain, negating anti-spoofing protection.",
        validator=spf_permissive,
    ),
    DnsRule(
        code="dns_dmarc_missing",
        severity=Severity.NOTICE,
        detail="A DMARC record at '_dmarc.<domain>' specifies how mail receivers should handle messages that fail SPF or DKIM checks.",
        validator=dmarc_missing,
    ),
    DnsRule(
        code="dns_dmarc_multiple",
        severity=Severity.WARNING,
        detail="Publishing more than one DMARC policy record is a misconfiguration; receivers cannot reliably determine which 'v=DMARC1' policy to apply.",
        validator=dmarc_multiple,
    ),
]
